<?php

namespace App\Services;

class SlangNormalizerService
{
    /**
     * Kamus bahasa gaul / slang Gen Z Indonesia lengkap.
     * Key   = kata slang / singkatan (lowercase)
     * Value = kata formal / sinonim untuk dikenali chatbot
     */
    private const SLANG_DICT = [
        // ─── Sapaan & Ekspresi Umum ────────────────────────────────────
        'halo'       => 'halo',
        'hai'        => 'halo',
        'hey'        => 'halo',
        'hei'        => 'halo',
        'oi'         => 'halo',
        'haloo'      => 'halo',
        'halooo'     => 'halo',
        'yo'         => 'halo',
        'assalamualaikum' => 'halo',
        'permisi'    => 'halo',
        'prmisi'     => 'halo',
        'misi'       => 'halo',
        'numpang'    => 'numpang tanya',

        // ─── Kata Ganti & Panggilan ────────────────────────────────────
        'gw'         => 'saya',
        'gue'        => 'saya',
        'gua'        => 'saya',
        'aku'        => 'saya',
        'q'          => 'saya',
        'w'          => 'saya',
        'lu'         => 'kamu',
        'lo'         => 'kamu',
        'loe'        => 'kamu',
        'elo'        => 'kamu',
        'kamu'       => 'kamu',
        'kau'        => 'kamu',
        'dia'        => 'dia',
        'doi'        => 'dia',
        'bro'        => '',
        'sis'        => '',
        'sob'        => '',
        'kak'        => '',
        'kakak'      => '',
        'guys'       => '',
        'bestie'     => '',
        'bestis'     => '',
        'gaes'       => '',
        'gan'        => '',
        'bos'        => '',

        // ─── Singkatan Pertanyaan ──────────────────────────────────────
        'gmn'        => 'gimana',
        'gimna'      => 'gimana',
        'bgmn'       => 'bagaimana',
        'bagmn'      => 'bagaimana',
        'kpn'        => 'kapan',
        'knp'        => 'kenapa',
        'knapa'      => 'kenapa',
        'napa'       => 'kenapa',
        'ngp'        => 'kenapa',
        'ap'         => 'apa',
        'apa2'       => 'apa-apa',
        'apaan'      => 'apa',
        'apasih'     => 'apa',
        'aps'        => 'apa',
        'dmn'        => 'dimana',
        'dimanaa'    => 'dimana',
        'mna'        => 'mana',
        'mnaa'       => 'mana',
        'siapa'      => 'siapa',
        'spaa'       => 'siapa',
        'spa'        => 'siapa',
        'brp'        => 'berapa',
        'brap'       => 'berapa',

        // ─── Kata Kerja Umum ───────────────────────────────────────────
        'mau'        => 'ingin',
        'mo'         => 'ingin',
        'pengen'     => 'ingin',
        'pingin'     => 'ingin',
        'pgn'        => 'ingin',
        'pngen'      => 'ingin',
        'butuh'      => 'perlu',
        'bth'        => 'perlu',
        'pake'       => 'pakai',
        'pkai'       => 'pakai',
        'make'       => 'pakai',
        'liat'       => 'lihat',
        'lht'        => 'lihat',
        'liet'       => 'lihat',
        'cek'        => 'cek',
        'ngecek'     => 'cek',
        'coba'       => 'coba',
        'nyoba'      => 'coba',
        'dpt'        => 'dapat',
        'dapet'      => 'dapat',
        'dapetin'    => 'dapat',
        'minta'      => 'minta',
        'mnta'       => 'minta',
        'nanya'      => 'tanya',
        'nanyain'    => 'tanya',
        'tanyain'    => 'tanya',
        'ngerti'     => 'mengerti',
        'tau'        => 'tahu',
        'taw'        => 'tahu',
        'gatau'      => 'tidak tahu',
        'gatahu'     => 'tidak tahu',
        'gtau'       => 'tidak tahu',
        'gk tau'     => 'tidak tahu',

        // ─── Negasi & Konfirmasi ───────────────────────────────────────
        'gak'        => 'tidak',
        'ga'         => 'tidak',
        'g'          => 'tidak',
        'ngga'       => 'tidak',
        'nggak'      => 'tidak',
        'gakk'       => 'tidak',
        'ndak'       => 'tidak',
        'ndk'        => 'tidak',
        'gk'         => 'tidak',
        'bkn'        => 'bukan',
        'bkn'        => 'bukan',
        'enggak'     => 'tidak',
        'engga'      => 'tidak',
        'iya'        => 'ya',
        'iyaa'       => 'ya',
        'yoi'        => 'ya',
        'yep'        => 'ya',
        'yapp'       => 'ya',
        'oke'        => 'oke',
        'ok'         => 'oke',
        'okeh'       => 'oke',
        'siap'       => 'oke',
        'siyap'      => 'oke',
        'oke sip'    => 'oke',
        'sip'        => 'oke',
        'sippp'      => 'oke',

        // ─── Kata Sifat & Ekspresi Perasaan ───────────────────────────
        'bingung'    => 'bingung',
        'bngung'     => 'bingung',
        'pusing'     => 'bingung',
        'ribet'      => 'rumit',
        'susah'      => 'sulit',
        'susyah'     => 'sulit',
        'sulit'      => 'sulit',
        'lupa'       => 'lupa',
        'kelupaan'   => 'lupa',
        'gampang'    => 'mudah',
        'gmnpang'    => 'mudah',
        'gampil'     => 'mudah',
        'guss'       => 'langsung',
        'gas'        => 'langsung',
        'gasss'      => 'langsung',
        'langsung'   => 'langsung',
        'segera'     => 'segera',
        'buru2'      => 'cepat',
        'buruan'     => 'cepat',
        'cepet'      => 'cepat',
        'cpet'       => 'cepat',

        // ─── Kata Hubung & Partikel ────────────────────────────────────
        'yg'         => 'yang',
        'yng'        => 'yang',
        'dg'         => 'dengan',
        'dgn'        => 'dengan',
        'sm'         => 'sama',
        'sama'       => 'sama',
        'ama'        => 'sama',
        'krn'        => 'karena',
        'karna'      => 'karena',
        'krna'       => 'karena',
        'kalo'       => 'kalau',
        'klo'        => 'kalau',
        'klw'        => 'kalau',
        'klau'       => 'kalau',
        'soal'       => 'tentang',
        'soalnya'    => 'karena',
        'jd'         => 'jadi',
        'jdi'        => 'jadi',
        'udh'        => 'sudah',
        'udah'       => 'sudah',
        'dah'        => 'sudah',
        'blm'        => 'belum',
        'blom'       => 'belum',
        'belom'      => 'belum',
        'msh'        => 'masih',
        'masi'       => 'masih',
        'sdh'        => 'sudah',
        'emg'        => 'memang',
        'emang'      => 'memang',
        'mmg'        => 'memang',

        // ─── Topik Pengaduan (Intent Keywords) ────────────────────────
        'lapor'      => 'lapor',
        'laporan'    => 'laporan',
        'ngelaporin' => 'laporan',
        'ngaduin'    => 'laporan',
        'aduin'      => 'laporan',
        'complain'   => 'pengaduan',
        'komplen'    => 'pengaduan',
        'komplen'    => 'pengaduan',
        'repot'      => 'pengaduan',
        'rusak'      => 'kerusakan',
        'rsk'        => 'kerusakan',
        'ancur'      => 'kerusakan',
        'hancur'     => 'kerusakan',
        'jebol'      => 'kerusakan',
        'ambruk'     => 'kerusakan',
        'mati'       => 'tidak berfungsi',
        'ngadat'     => 'tidak berfungsi',
        'trouble'    => 'masalah',
        'trobel'     => 'masalah',
        'error'      => 'masalah',
        'eror'       => 'masalah',
        'gak jalan'  => 'tidak berfungsi',
        'gak nyala'  => 'tidak berfungsi',
        'mati lampu' => 'listrik mati',
        'bocor'      => 'bocor',
        'retak'      => 'retak',
        'pecah'      => 'rusak',
        'patah'      => 'rusak',

        // ─── Topik Pinjaman (Intent Keywords) ─────────────────────────
        'pinjem'     => 'pinjam',
        'minjam'     => 'pinjam',
        'minjem'     => 'pinjam',
        'pinjamin'   => 'pinjam',
        'pinjemen'   => 'pinjam',
        'minjem'     => 'pinjam',
        'ngminjem'   => 'pinjam',
        'pnjem'      => 'pinjam',
        'balikin'    => 'kembalikan',
        'ngembaliin' => 'kembalikan',
        'ngembalikan'=> 'kembalikan',
        'return'     => 'kembalikan',
        'retur'      => 'kembalikan',
        'stok'       => 'stok',
        'stock'      => 'stok',
        'barang'     => 'barang',
        'brg'        => 'barang',
        'available'  => 'tersedia',

        // ─── Status & Tracking ──────────────────────────────────────────
        'status'     => 'status',
        'gmn statusnya' => 'status pengaduan saya',
        'gimana statusnya' => 'status pengaduan saya',
        'udh sampe mana' => 'status pengaduan saya',
        'udah diproses' => 'status pengaduan',
        'diproses blm' => 'status pengaduan',
        'track'      => 'lacak',
        'lacak'      => 'lacak',
        'tracking'   => 'lacak',
        'lanjut'     => 'lanjut',
        'update'     => 'perkembangan',
        'perkembangan' => 'perkembangan',
        'progres'    => 'perkembangan',
        'progress'   => 'perkembangan',

        // ─── Fasilitas & Lokasi ────────────────────────────────────────
        'kelas'      => 'ruangan',
        'lab'        => 'laboratorium',
        'kantin'     => 'kantin',
        'toilet'     => 'toilet',
        'wc'         => 'toilet',
        'kamar mandi'=> 'toilet',
        'perpus'     => 'perpustakaan',
        'parkiran'   => 'parkir',
        'gym'        => 'olahraga',
        'lapangan'   => 'lapangan',
        'kantor'     => 'kantor',
        'tata usaha' => 'tata usaha',
        'tu'         => 'tata usaha',
        'bp'         => 'bimbingan konseling',
        'bk'         => 'bimbingan konseling',

        // ─── Kategori Kerusakan Umum ───────────────────────────────────
        'listrik'    => 'listrik',
        'lampu'      => 'listrik',
        'stop kontak'=> 'listrik',
        'colokan'    => 'listrik',
        'proyektor'  => 'proyektor',
        'projector'  => 'proyektor',
        'lcd'        => 'proyektor',
        'ac'         => 'ac',
        'kipas'      => 'ac',
        'air'        => 'plumbing',
        'keran'      => 'plumbing',
        'kran'       => 'plumbing',
        'pipa'       => 'plumbing',
        'kursi'      => 'furnitur',
        'bangku'     => 'furnitur',
        'meja'       => 'furnitur',
        'papan tulis' => 'furnitur',
        'whiteboard' => 'furnitur',
        'pintu'      => 'bangunan',
        'jendela'    => 'bangunan',
        'tembok'     => 'bangunan',
        'dinding'    => 'bangunan',
        'atap'       => 'bangunan',
        'lantai'     => 'bangunan',
        'tangga'     => 'bangunan',
        'pagar'      => 'bangunan',

        // ─── Bahasa Gaul Gen Z 2024-2025 ──────────────────────────────
        'gercep'     => 'cepat',
        'gerak cepat'=> 'cepat',
        'skuy'       => 'ayo',
        'skoy'       => 'ayo',
        'yukk'       => 'ayo',
        'yuk'        => 'ayo',
        'gasken'     => 'ayo langsung',
        'gaskeunn'   => 'ayo langsung',
        'cuss'       => 'ayo langsung',
        'cusss'      => 'ayo langsung',
        'kepo'       => 'ingin tahu',
        'kepoin'     => 'ingin tahu',
        'spill'      => 'ceritakan',
        'spill dong' => 'ceritakan',
        'nanya dong' => 'tanya',
        'tanya dong' => 'tanya',
        'tanya nih'  => 'tanya',
        'mager'      => 'malas',
        'males'      => 'malas',
        'malas'      => 'malas',
        'bucin'      => 'terlalu peduli',
        'gabut'      => 'tidak ada kegiatan',
        'gajelas'    => 'tidak jelas',
        'gaje'       => 'tidak jelas',
        'anjay'      => '',     // ekspresi netral, abaikan
        'anjir'      => '',
        'astaga'     => '',
        'duh'        => '',
        'wah'        => '',
        'wkwk'       => '',
        'wkwkwk'     => '',
        'haha'       => '',
        'hehe'       => '',
        'hehehe'     => '',
        'lol'        => '',
        'kwkwk'      => '',
        'ngakak'     => '',
        'auto'       => 'langsung',
        'literally'  => 'benar-benar',
        'frfr'       => 'benar-benar',
        'fr fr'      => 'benar-benar',
        'no cap'     => 'serius',
        'nocap'      => 'serius',
        'cap'        => 'bohong',
        'deadass'    => 'serius',
        'pov'        => 'situasi',
        'plot twist' => 'tidak terduga',
        'sus'        => 'mencurigakan',
        'red flag'   => 'peringatan',
        'green flag'  => 'baik',
        'vibe'       => 'nuansa',
        'vibes'      => 'nuansa',
        'healing'    => 'istirahat',
        'hits'       => 'populer',
        'hype'       => 'populer',
        'santuy'     => 'santai',
        'santai'     => 'santai',
        'baper'      => 'terbawa perasaan',
        'galau'      => 'bingung/sedih',
        'overthinking' => 'terlalu banyak pikiran',
        'drama'      => 'masalah',
        'receh'      => 'sepele',
        'lebay'      => 'berlebihan',
        'alay'       => 'berlebihan',
        'savage'     => 'berani',
        'kece'       => 'keren',
        'keren'      => 'bagus',
        'mantap'     => 'bagus',
        'mantul'     => 'bagus',
        'mantappu jiwa' => 'bagus',
        'top'        => 'bagus',
        'topbgt'     => 'sangat bagus',
        'bgt'        => 'sangat',
        'banget'     => 'sangat',
        'bngd'       => 'sangat',
        'bgtt'       => 'sangat',
        'poll'       => 'sangat',
        'parah'      => 'sangat',
        'parahh'     => 'sangat',
        'gila'       => 'luar biasa',
        'gilaa'      => 'luar biasa',
        'gilaaa'     => 'luar biasa',

        // ─── Singkatan Sosmed ──────────────────────────────────────────
        'btw'        => 'ngomong-ngomong',
        'fyi'        => 'perlu diketahui',
        'imo'        => 'menurut saya',
        'imho'       => 'menurut saya',
        'tbc'        => 'masih akan dikonfirmasi',
        'tbh'        => 'jujur',
        'afaik'      => 'sejauh yang saya tahu',
        'asap'       => 'segera',
        'ngl'        => 'jujur',
        'idk'        => 'tidak tahu',
        'idc'        => 'tidak peduli',
        'irl'        => 'di kehidupan nyata',
        'ootd'       => 'pakaian hari ini',
        'dm'         => 'pesan langsung',
        'otw'        => 'dalam perjalanan',
        'otw nih'    => 'sedang dalam perjalanan',
        'wts'        => 'dijual',
        'wtb'        => 'dicari',
        'thx'        => 'terima kasih',
        'makasih'    => 'terima kasih',
        'mks'        => 'terima kasih',
        'mksh'       => 'terima kasih',
        'trm ksh'    => 'terima kasih',
        'suwun'      => 'terima kasih',
        'tq'         => 'terima kasih',
        'ty'         => 'terima kasih',
        'np'         => 'sama-sama',
        'sami sami'  => 'sama-sama',
        'sami2'      => 'sama-sama',

        // ─── Singkatan Teks Indonesia ──────────────────────────────────
        'yth'        => 'yang terhormat',
        'tsb'        => 'tersebut',
        'dst'        => 'dan seterusnya',
        'dll'        => 'dan lain-lain',
        'dlm'        => 'dalam',
        'utk'        => 'untuk',
        'tuk'        => 'untuk',
        'dr'         => 'dari',
        'dr.'        => 'dari',
        'pd'         => 'pada',
        'dg'         => 'dengan',
        'tp'         => 'tapi',
        'tpi'        => 'tapi',
        'ttg'        => 'tentang',
        'hrs'        => 'harus',
        'hrs'        => 'harus',
        'dpt'        => 'dapat',
        'sdh'        => 'sudah',
        'blm'        => 'belum',
        'sgt'        => 'sangat',
        'jg'         => 'juga',
        'lg'         => 'lagi',
        'lgsg'       => 'langsung',
        'bs'         => 'bisa',
        'bisa'       => 'bisa',
        'bsa'        => 'bisa',
        'bs gk'      => 'bisa tidak',
        'bisa gak'   => 'bisa tidak',
        'mgkn'       => 'mungkin',
        'mungkin'    => 'mungkin',
        'skrg'       => 'sekarang',
        'skrang'     => 'sekarang',
        'skarang'    => 'sekarang',
        'hr ini'     => 'hari ini',
        'hri ini'    => 'hari ini',
        'hari ini'   => 'hari ini',
        'bsok'       => 'besok',
        'bsk'        => 'besok',
        'kmrn'       => 'kemarin',
        'kemrn'      => 'kemarin',

        // ─── Gen Alpha (2025) ──────────────────────────────────────────
        'stecu'      => 'ekspresi kaget',
        'sigma'      => 'mandiri/keren',
        'rizz'       => 'daya tarik',
        'slay'       => 'keren/berhasil',
        'bussin'     => 'enak/bagus sekali',
        'sus'        => 'mencurigakan',
        'npc'        => 'tidak penting',
        'based'      => 'benar/setuju',
        'lowkey'     => 'sedikit/diam-diam',
        'highkey'    => 'sangat/jelas-jelas',
        'bet'        => 'setuju/oke',
        'bro'        => '',
        'bruh'       => '',
        'sheesh'     => '',
        'mid'        => 'biasa saja',
        'it\'s giving' => 'terlihat seperti',
        'understood the assignment' => 'berhasil',
        'era'        => 'fase',
        'delulu'     => 'tidak realistis',
        'snatched'   => 'bagus sekali',
        'ate'        => 'berhasil melakukan dengan baik',
        'periodt'    => 'titik/sudah selesai',
        'ick'        => 'tidak menarik',
        'touch grass' => 'keluar dari online',
        'rent free'  => 'terus terpikir',
        'main character' => 'tokoh utama',
        'understood' => 'mengerti',
        '67'         => 'ekspresi gaul',
        'skibidi'    => 'ekspresi gaul',
        'gyatt'      => 'ekspresi kaget',
        'rizzing'    => 'menggoda',
        'zesty'      => 'bersemangat',
        'ohio'       => 'aneh',
        'sussy'      => 'mencurigakan',
        'poggers'    => 'keren',
        'pog'        => 'keren',
        'cap'        => 'bohong',
        'no cap'     => 'tidak bohong',
        'goat'       => 'terbaik',
        'gg'         => 'bagus',

        // ─── Topik Spesifik SFCS ──────────────────────────────────────
        'pengumuman' => 'informasi',
        'info'       => 'informasi',
        'inpo'       => 'informasi',
        'banyak ga'  => 'berapa banyak',
        'berapa lama' => 'berapa lama',
        'lama gak'   => 'berapa lama',
        'kapan selesai' => 'kapan selesai',
        'kapan jadi' => 'kapan selesai',
        'kapan dong' => 'kapan',
        'bantu dong' => 'bantuan',
        'tolong'     => 'bantuan',
        'help dong'  => 'bantuan',
        'help me'    => 'bantuan',
        'bisa bantu' => 'bantuan',
        'ada masalah' => 'ada masalah',
        'masalah nih' => 'ada masalah',
        'problem'    => 'masalah',
        'kenapa'     => 'kenapa',
        'knapa'      => 'kenapa',
        'kok bisa'   => 'mengapa',
        'kok gitu'   => 'mengapa',
        'kok gini'   => 'mengapa',
        'caranya gmn' => 'bagaimana caranya',
        'caranya gimana' => 'bagaimana caranya',
        'cara nya'   => 'bagaimana caranya',
        'langkahnya' => 'bagaimana caranya',
        'stepnya'    => 'bagaimana caranya',
        'tutornya'   => 'tutorial',
        'tutor'      => 'tutorial',
        'tata cara'  => 'bagaimana caranya',
    ];

    /**
     * Normalize a message: expand slang, remove filler words, lowercase.
     */
    public function normalize(string $message): string
    {
        $text = mb_strtolower(trim($message));

        // Hapus karakter berulang berlebihan: "gakkkk" → "gak", "baguuuus" → "bagus"
        $text = preg_replace('/(.)\1{2,}/', '$1$1', $text);

        // Ganti slang kata per kata dengan word boundary aware approach
        foreach (self::SLANG_DICT as $slang => $formal) {
            // Coba exact substring match dengan spasi/batas kata
            $escaped = preg_quote($slang, '/');
            $text    = preg_replace('/(?<![a-z])' . $escaped . '(?![a-z])/', ' ' . $formal . ' ', $text);
        }

        // Bersihkan spasi ganda
        $text = preg_replace('/\s+/', ' ', trim($text));

        return $text;
    }

    /**
     * Deteksi apakah pesan mengandung nuansa gaul / informal
     * agar chatbot bisa membalas dengan lebih santai jika diperlukan.
     */
    public function isInformal(string $message): bool
    {
        $informalMarkers = [
            'gw', 'gue', 'gua', 'lu', 'lo', 'bro', 'sis', 'guys',
            'dong', 'nih', 'deh', 'sih', 'lah', 'aja', 'wkwk', 'hehe',
            'gak', 'ga', 'ngga', 'gasken', 'skuy', 'yoi', 'btw',
        ];
        $lc = mb_strtolower($message);
        foreach ($informalMarkers as $m) {
            if (str_contains($lc, $m)) return true;
        }
        return false;
    }

    /**
     * Expand common typos and abbreviations in the original string
     * sebelum diproses lebih lanjut.
     */
    public function expandAbbreviations(string $message): string
    {
        $patterns = [
            // Ganda huruf vokal berlebihan
            '/a{3,}/'    => 'a',
            '/e{3,}/'    => 'e',
            '/i{3,}/'    => 'i',
            '/o{3,}/'    => 'o',
            '/u{3,}/'    => 'u',
            // Tanda tanya/seru berlebihan
            '/[?!]{2,}/' => '?',
        ];

        foreach ($patterns as $pattern => $replacement) {
            $message = preg_replace($pattern, $replacement, $message);
        }

        return $message;
    }
}
