[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache",
    "npm run build",
    "php artisan config:cache",
    "php artisan event:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[phases.deploy]
cmds = [
    "php artisan migrate --force",
    "php artisan db:seed --force",
    "php artisan storage:link"
]

[variables]
NIXPACKS_PHP_VERSION = "8.4"
